### ISSUE TITLE
Saving new passwords via popup does not work

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman-webextension#153] opened 2017-08-06 14:50 UTC
### Steps to reproduce
Click on save here:
![savepass](https://user-images.githubusercontent.com/11966684/29004439-31ca2536-7ac7-11e7-9fbe-e0c20547f195.png)

### Expected behaviour
Save password, hide popup and maybe input it directly into password box.

### Actual behaviour
Nothing happens. Not even the console logs something.

### Configuration
**Operating system**: Linux

**Browser**: FF 54.0.1

**Passman version**: 2.1.4

**Extension version**: 2.0.0

**Nextcloud version**: 12

**Comment by brantje** [comment] 2017-08-06 14:52
Duplicate of #128 will be solved when Mozilla approves the next version. 
![image](https://user-images.githubusercontent.com/2758767/29004459-a77c3b98-7ac7-11e7-84f0-16303c617d17.png)

**Closed** 2017-08-06 14:52 UTC
