### ISSUE TITLE
Chrome Extension constantly eating CPU

### ISSUE THREAD

**Issue by mobamoba** [nextcloud/passman-webextension#225] opened 2017-12-20 14:59 UTC
### Steps to reproduce
1. Happens constantly.
2. 
3. 

### Expected behaviour
Tell us what should happen

When idle, the Passman Extension should be doing little to nothing.

### Actual behaviour
Tell us what happens instead
Passman eating enormous amounts of CPU at all times regardless of whether it's being used or not.

### Configuration
**Operating system**: 
Chrome OS
**Browser**: 
Chrome 64 beta
**Extensions that might cause interference**: 

**Passman version**: 
2.14
**Extension version**: 
2.04
**Nextcloud version**: 
   13 beta 3
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by brantje** [comment] 2017-12-20 14:59
I thinks is is a dupe of #201, closing

**Closed by brantje** 2017-12-20 14:59 UTC

**Comment by mobamoba** [comment] 2017-12-20 15:02
Okay. I don't have the hanging though, just sluggishness and, when I check the Chrome Task Manager, I see the CPU usage of the Passman extension being extremely high.

**Comment by brantje** [comment] 2017-12-20 15:04
![image](https://user-images.githubusercontent.com/2758767/34213416-742c8f2a-e59f-11e7-8524-82a71fd3bd92.png)
3% isn't much to me. 
Can you tell me the configuration of your pc and a screenshot of chrome's task manager?

**Comment by mobamoba** [comment] 2017-12-21 13:00
I'm using an Acer Chromebook R11
Processor: 1.6GHz quad-core Intel Celeron N3150 (quad-core, 3MB cache, up to 2.08GHz with Turbo Boost)
Graphics: Integrated Intel HD Graphics.
Memory: 4GB DDR3L.

What other info would be helpful to pass along to you?
The screenshot below is an example of the high CPU usage when Passman is doing absolutely nothing - I was just browsing a website:

![screenshot 2017-12-21 at 7 56 10 am](https://user-images.githubusercontent.com/11135869/34256755-d7411bdc-e624-11e7-951a-f67f32f4d240.png)

**Comment by mobamoba** [comment] 2017-12-21 13:07
Here's another example. This was Passman usage after visiting the NY Times website for a few minutes - I wasn't doing anything, not logging in, not switching pages, not even reading the article; it was simply an open tab in my browser. I switched back to it, let it "settle" for a few minutes then took this screenshot of the Task Manager:

![imageedit_2_5755460713](https://user-images.githubusercontent.com/11135869/34257005-fd045914-e625-11e7-8f59-63ac4007374c.jpg)

**Comment by brantje** [comment] 2017-12-21 13:09
How many vaults do you have configured? And what is the total number of credentials?
Just tested with the NY Times site, here is the result:
![image](https://user-images.githubusercontent.com/2758767/34257071-9be54912-e658-11e7-840d-d05ff1f22ab1.png)

**Comment by mobamoba** [comment] 2017-12-21 13:11
1 vault. 864 credentials.

I'm on Chrome 64 beta. Perhaps Google made a change that's affecting the extension?

**Comment by brantje** [comment] 2017-12-21 13:13
Possible. Otherwise it might be that the page content changes frequently, what triggers the extension to scan for forms.
Do you have this on all websites or just some?

**Comment by mobamoba** [comment] 2017-12-21 13:15
Everywhere to varying degrees. Passman is never at 0 no matter what site I'm on. It drops as low as 5-10 and I've seen it as high as 90-100. Again, this is just when browsing and not when it's actually in use.

**Comment by mobamoba** [comment] 2017-12-21 13:16
Even just sitting here on Github, it's jumping from 7% to 18%.

**Comment by brantje** [comment] 2017-12-21 13:17
Yea, the extension has background job(s). Meaning fetching new credentials, decrypting them and storing them in memory.

**Comment by mobamoba** [comment] 2017-12-21 13:20
Are you saying that using 23% of my CPU is normal for an extension that's doing nothing? Because your example had Passman at 0, which I never have.

Is there a way to debug this better so you can see why it's using so much CPU?

**Comment by animalillo** [comment] 2017-12-21 13:22
To check for passman behaviour open the browser with just a single tab with a static content, unlock the extension and check cpu usage

**Comment by animalillo** [comment] 2017-12-21 13:28
We can't fix a problem without being able to replicate it first.

And beta software is not fully reliable, some weird stuff can happen. So i think it's safe if this only happens on the beta chrome.

Also same site does not mean same page or same open tabs. There is a lot that can be going on your side that we don't know

**Comment by mobamoba** [comment] 2017-12-21 13:30
Right, that's why I wanted to know if there was other debugging information I could pass along other than screenshots of my CPU usage that might show you what's going on with Passman under the hood and help understand what's generating that high CPU usage.
