### ISSUE TITLE
Overrides manual input, forced to use saved password [$10]

### ISSUE THREAD

**Issue by gregf** [nextcloud/passman-webextension#202] opened 2017-11-02 18:39 UTC
Sometimes I may have multiple accounts for a site, or the password saved is no longer valid and I'm trying to manually type in the user/pass for whatever reason. Passman will not let me delete what is filled in and change anything. It constantly forces the fields to be filled in, instead of just once on load. 

The only way to avoid this currently is to disable the extension in chrome currently then re-enable later.

**Comment by brantje** [comment] 2017-11-02 18:40
Duplicate of #185

**Comment by nodauf** [comment] 2017-11-04 15:55
@brantje I think it is not the same issue. In the issue #185 it seems it's the website which have a strange behavior.
In this issue, it's passman which override a password manually type.

For example on a website I want to change my password. Unfortunately, passman fill the field for new password and for old password. I change the new password and passman keep filling the field. So to change my password I need to lock the extension to avoid that passman fill the field.
I have this behavior on every websites.

**Comment by brantje** [comment] 2017-11-04 15:56
Yea saw it happening too.

**Closed** 2018-04-02 13:34 UTC
Labels: bounty, review
