### ISSUE TITLE
Chrome plugin does not save passwords

### ISSUE THREAD

**Issue by marcoreni** [nextcloud/passman-webextension#222] opened 2017-12-10 13:20 UTC
### Steps to reproduce
1. Use a Nextcloud server with multiple vaults
2. Interactively save a login via the extension
3. Check if the login has been saved

### Expected behaviour
The login should have been saved

### Actual behaviour
Extension does not returns error, but the login is not saved.

### Configuration
**Operating system**:  Win10 64bit

**Browser**: Chrome 62.0 64bit

**Passman version**: latest

**Extension version**: latest

**Nextcloud version**: 12.0.3
   
#### Nextcloud log
```Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_passman_credentials`(`guid`,`user_id`,`label`,`description`,`created`,`changed`,`tags`,`email`,`username`,`password`,`url`,`expire_time`,`delete_time`,`files`,`custom_fields`,`otp`,`hidden`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)' ...... SQLSTATE[HY000]: General error: 1364 Field 'vault_id' doesn't have a default value```

**Comment by Houtworm** [comment] 2017-12-23 17:18
I have the same problem on Linux with Firefox. Passwords save for the session in the Passman Extension but never show up in Nextcloud. A workaround is adding the passwords manually in nextcloud but this doesnt work for me, Hoping this will get patched soon. I tried to reinstall everything even tried a fresh nextcloud install and another computer, Same problem persists.

**Comment by brantje** [comment] 2017-12-24 10:38
Have some time to check later this week

**Comment by jzielke-nli** [comment] 2018-01-15 20:35
Also I have noticed that on windows chrome passman asks me to update the URL while on the mac os X version of chrome it doesn't. Weird...

**Comment by brantje** [comment] 2018-04-01 09:38
Dupe of #221 i think. Otherwise i'll reopen it.

**Closed by brantje** 2018-04-01 09:38 UTC

**Comment by marcoreni** [comment] 2018-04-03 14:06
I'm not sure this is a duplicate, since in my case the issue was with the automatic popup, but using more than one vault.

Anyway, I migrated to a different system so I'm not able to help anymore.
