### ISSUE TITLE
saving passwords to vault not working

### ISSUE THREAD

**Issue by tripcreator** [nextcloud/passman-webextension#19] opened 2017-02-27 13:01 UTC
### Steps to reproduce
1. login to new site
2. click save credentials
3. check vault --> no new credentials added

### Expected behaviour
credentials should be saved in the vault

### Actual behaviour
credentials don´t show up in the vault
but they are visible in the chrome / firefox extension

### Configuration
**Operating system**:   
macOS 10.12
   
**Browser**:   
   firefox 51.01
chrome
chromium Version 58.0.3023.0
      
 
**Passman version**:    
   2.1.1    
Vault Name: it
       
**Nextcloud version**:
   11.0.2
   11.0.1
**Nextcloud Error Logging**

Error	PHP	Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85	2017-02-27T13:43:49+0100
Error	PHP	vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72	2017-02-27T13:43:49+0100
Error	PHP	Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85	2017-02-27T13:43:22+0100
Error	PHP	vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72	2017-02-27T13:43:22+0100
Error	PHP	Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85	2017-02-27T13:43:12+0100
Error	PHP	vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72	2017-02-27T13:43:12+0100
Error	PHP	Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85	2017-02-27T13:37:02+0100
Error	PHP	vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72	2017-02-27T13:37:02+0100
Error	PHP	Object of class OC\User\User could not be converted to string at /var/www/nextcloud/lib/private/legacy/util.php#1126	2017-02-27T13:36:50+0100
Error	passman	Could not find resource file "/apps/passman/css/vendor/font-awesome/font-awesome.min.css"

**Comment by jones4410** [comment] 2017-02-27 14:57
same for me...

**Comment by Matttter** [comment] 2017-03-07 18:23
I have this issue too. Is there a fix somehow?

**Comment by brantje** [comment] 2017-03-08 09:07
Not yet i'll might make a fix this weekend

**Comment by Matttter** [comment] 2017-03-08 09:43
Thanks in advance for your efforts! If you need anything (logs or stuff) just fire off a comment

**Comment by brantje** [comment] 2017-03-08 09:44
Problem traced to: onClick event is not firing.

**Comment by jones4410** [comment] 2017-03-12 15:16
works for me with passman-webextension 1.0.3

**Comment by Matttter** [comment] 2017-03-12 16:29
Doesn't work for me with either chrome or firefox. Maybe this is server-side? Am I missing a dependency somehow?

**Comment by Matttter** [comment] 2017-03-19 08:38
I'm so sorry, I confused this with an issue I'm having. I created a new issue, but saving credentials works fine for me

**Comment by brantje** [comment] 2017-04-08 14:03
Found the issue, when creating the credential from the password picker the function was called.
But i forgot to register the function in the `background.js`. This is fixed in the upcoming release.
Thanks for reporting =)

**Closed by brantje** 2017-04-08 14:03 UTC
Labels: bug

**Comment by fyah** [comment] 2017-12-19 12:54
Hello,

I just started to use passman with FF extension 2.0.4 and NextCloud 12.0.4 & passman  2.1.4 app.

I get the exact same symptom:
Error	PHP	Method OC_L10N_String::__toString() must return a string value at /volume1/web/owncloud/lib/private/L10N/L10N.php#85
Error	PHP	vsprintf(): Too few arguments at /volume1/web/owncloud/lib/private/legacy/l10n/string.php#72

Nothing goes to the vault.
Credentials stays in the FF extension

same way to reproduce, create the credentials from the password picker (generator)

Thanks a lot for your help !
