### ISSUE TITLE
Missing stored credential numbers in translated addon

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#51] opened 2017-05-05 11:15 UTC
### Steps to reproduce
1. Use the translated addon.
2. Click on the icon

### Expected behaviour
You should see the total number of the stored credentials

### Actual behaviour
No number appears

**Browser**: Firefox 53
**Passman version**: 2.1.1
**Extension version**:  1.2.4
**Nextcloud version**: 11.0.3

![Like This](http://i.imgur.com/FS8nC47.png)

**Comment by adocampo** [comment] 2017-05-05 11:16
By the way, I've also submitted some changes on transifex spanish translations, if @animalillo want to take a look to them and see if he is agree with changing them

**Comment by brantje** [comment] 2017-05-05 13:24
Jup, transifex is deleting the placeholders: https://github.com/nextcloud/passman-webextension/commit/fd534b2ebbc3e2f4546bf4da44ee350f38fa8fb3

**Comment by brantje** [comment] 2017-05-05 15:43
![image](https://cloud.githubusercontent.com/assets/2758767/25752994/479d2dc8-31ba-11e7-912e-90545feb28ca.png)

**Comment by brantje** [comment] 2017-05-06 18:30
Fixed with a script in `1.2.5`

**Closed by brantje** 2017-05-06 18:30 UTC

**Comment by brantje** [comment] 2017-05-07 08:47
@adocampo Can you confirm the issue is solved?

**Comment by adocampo** [comment] 2017-05-07 09:39
So far so good, it's hard to see a placeholder on the new version... perhaps under settings passman version?

**Comment by adocampo** [comment] 2017-05-07 10:09
Where is supossed to appear "**Passman - $CREDENTIAL_AMOUNT$ $PLURAL$ found for this page**
Because on 1.2.4 or earlier was placed on the top of the widget when entering a site and clicked on the icon, now just appears a list of the credentials founded.
![Like this](http://pix.toile-libre.org/upload/original/1494151757.png)

**Comment by adocampo** [comment] 2017-05-07 10:21
Oh, I've just saw wher that parameter is shown, is just a tooltip placed over the passman icon :)

Solved! :)
