### ISSUE TITLE
passwords with ampersand

### ISSUE THREAD

**Issue by JediBrooker** [nextcloud/passman-webextension#237] opened 2018-02-11 06:31 UTC
### Steps to reproduce
1. click on extension icon to open
2. search for password
3. view password

### Expected behaviour
Passwords with ampersand (&) symbol should show as normal within the password

### Actual behaviour
The ampersand is shown but immediately after the ampersand symbol it shows "amp;" as in `"&amp;"`

### Configuration
**Operating system**: Manjaro Linux

**Browser**: Firefox Quantum

**Extensions that might cause interference**: 

**Passman version**: 2.1.4

**Extension version**: 2.0.4

**Nextcloud version**: 13

**Comment by brantje** [comment] 2018-04-01 09:46
Dupe of #178

**Closed by brantje** 2018-04-01 09:46 UTC
Labels: bug
