### ISSUE TITLE
Cannot unlock extension

### ISSUE THREAD

**Issue by adocampo** [nextcloud/passman-webextension#17] opened 2017-02-24 17:23 UTC
### Steps to reproduce
1. Set up master password
2. Lock the extension via lock icon
3. Enter the password to unlock

### Expected behaviour
It should unlock

### Actual behaviour
A message appears:  Invalid master password! 
And it does not unlocks.

### Configuration
NC Server: Arch linux docker container
Client: Arch linux client
   
**Browser**:   
   Both Firefox and Chromium
   
**Extensions that might cause interference**:   
   None, all disable just to try
   
**Passman version**:    
   2.1.1    
       
**Nextcloud version**:
   11.0.1

**Comment by brantje** [comment] 2017-02-24 17:25
Duplicate of #5

**Closed by brantje** 2017-02-24 17:25 UTC
